def count_nucleotides(s):
    counts = {'A': 0, 'C': 0, 'G': 0, 'T': 0}
    for char in s:
        if char in counts:
            counts[char] += 1
    return counts['A'], counts['C'], counts['G'], counts['T']
    
    
    
s = "CGGTTCAGCAGTCGCTACGAGATCAAGGGCTTGTGACCGAGTCCCTGCGACTTTAACTGATTGTCGCATATTGTCCGTCGCATCCCCCGCAACCCGTCCGGTGGGCACTGCCATATCTCCCCGCCAATATCGTTCGATTCGGCCCCTTAAGTGCCTCGTATTCATGTACACAACTTAGATATGGTGCTGACTGGCTTCCTAACTCGGGCGCACTCAGCCGATCCATGCATTGAGGCCACCCGAGCGCGCGCCAAACCAATCGCCTGAGCTAACAGTTTGAGGTGTCTGAATGACCCTGAGTTGGTCGTCATCTACTCTGCCGTTACACGTCTGCCGCACAAATCTCACGACTGAAGGTTTAGTTGTGACAGGTGCCATACAGAGTCTTACTCTTCTAGCCAGCATTCGGATTCTCCCAAGTAGGTTAGCCGAAACAGCGCTGCAGCCTTCCCGAATTAGATTTAAGCATCTGCGCCACTGCAATCCTAATCCGCATAGCCCATCAGCGGTGGTACTACATAATCGGTATACGACAGTCCCGAGTCTTGCATGTACAACTGGCGTCGCCGTCAACATAAGTCGCAGGTCAACATGAGACCGGATGAAGAACTCATCGGGAGCGAAGCGAGACCGGCAAGAGACTTCCGCAACCAAGTGGATCTAAGACGCCTGTACTATCCATAAACCCCTGCATCCTCATAGACGAAAAGCTTAGTCCGCGCCGTGTCGGCGCTGTTGCCTTAGGGCATGGGCAAATGTCGTGCGCGGCTAGTGTGACTCCCAATCTTCGTCTCATGGGACTGCTTTGAGCTCGGCTGATTGTAACAGTAACACATATGAACGGTCAAATCGGGCTGTTCTATACTATTTCTCGTTGGTTCGACATGAATTAAGACAAGATCGTG"
result = count_nucleotides(s)
print(result)
